### ISSUE TITLE
x86 binary release sometimes fails

### ISSUE THREAD

**Issue by thinca** [vim/vim-win32-installer#262]
### Steps to reproduce

In some cases, x86 binaries are not released.

ex.
- https://github.com/vim/vim-win32-installer/releases/tag/v8.2.5046
  - Log on AppVeyor: https://ci.appveyor.com/project/chrisbra/vim-win32-installer/builds/43704899/job/xd7c4tyd1i098kiv
- https://github.com/vim/vim-win32-installer/releases/tag/v8.2.5034
  - Log on AppVeyor: https://ci.appveyor.com/project/chrisbra/vim-win32-installer/builds/43685506/job/tga486p4vahg5u0p

It can be successful.  The last 20 histories are below.

- [v8.2.5052](https://github.com/vim/vim-win32-installer/releases/tag/v8.2.5052) Success
- [v8.2.5048](https://github.com/vim/vim-win32-installer/releases/tag/v8.2.5048) Success
- [v8.2.5046](https://github.com/vim/vim-win32-installer/releases/tag/v8.2.5046) Failure
- [v8.2.5041](https://github.com/vim/vim-win32-installer/releases/tag/v8.2.5041) Success
- [v8.2.5037](https://github.com/vim/vim-win32-installer/releases/tag/v8.2.5037) Success
- [v8.2.5034](https://github.com/vim/vim-win32-installer/releases/tag/v8.2.5034) Failure
- [v8.2.5026](https://github.com/vim/vim-win32-installer/releases/tag/v8.2.5026) Success
- [v8.2.5018](https://github.com/vim/vim-win32-installer/releases/tag/v8.2.5018) Success
- [v8.2.5014](https://github.com/vim/vim-win32-installer/releases/tag/v8.2.5014) Success
- [v8.2.5010](https://github.com/vim/vim-win32-installer/releases/tag/v8.2.5010) Success
- [v8.2.5006](https://github.com/vim/vim-win32-installer/releases/tag/v8.2.5006) Success
- [v8.2.4995](https://github.com/vim/vim-win32-installer/releases/tag/v8.2.4995) Failure
- [v8.2.4987](https://github.com/vim/vim-win32-installer/releases/tag/v8.2.4987) Success
- [v8.2.4981](https://github.com/vim/vim-win32-installer/releases/tag/v8.2.4981) Failure
- [v8.2.4980](https://github.com/vim/vim-win32-installer/releases/tag/v8.2.4980) Success
- [v8.2.4975](https://github.com/vim/vim-win32-installer/releases/tag/v8.2.4975) Failure
- [v8.2.4969](https://github.com/vim/vim-win32-installer/releases/tag/v8.2.4969) Failure
- [v8.2.4960](https://github.com/vim/vim-win32-installer/releases/tag/v8.2.4960) Failure
- [v8.2.4956](https://github.com/vim/vim-win32-installer/releases/tag/v8.2.4956) Failure
- [v8.2.4950](https://github.com/vim/vim-win32-installer/releases/tag/v8.2.4950) Failure

### Expected behaviour

x86 binaries are released correctly.

### Version of Vim

x86 version

### Environment

AppVeyor

**Comment by k-takata** [comment]
Hmm, it looks like test_alot.vim stalls. We need to analyze it.

Another way to avoid this would be to reorganize the CI and create a release only when both x64 and x86 are successfully built. But,
* I don't know how to do this on AppVeyor.
* I already do this on GitHub Actions on [another project](https://github.com/k-takata/vim-kt), but I don't know whether SignPath can be used via GHA.

**Comment by k-takata** [comment]
> * I don't know how to do this on AppVeyor.

Maybe, this can be used https://www.appveyor.com/docs/job-workflows/.

> * I already do this on GitHub Actions on [another project](https://github.com/k-takata/vim-kt), but I don't know whether SignPath can be used via GHA.

GHA is not listed here: https://about.signpath.io/documentation/trusted-build-systems

**Comment by k-takata** [comment]
> Maybe, this can be used https://www.appveyor.com/docs/job-workflows/.

I worked around this in #263 in a different way. The above way was more complex than GHA's jobs and steps structure.

We still need to analyze the reason why test_alot.vim stops, though.

**Comment by k-takata** [comment]
I confirmed that today's build is not published because the x86 build failed.
![image](https://user-images.githubusercontent.com/840186/172265519-f424394e-2cdf-4dc0-8092-eb9bddad42fd.png)

**Comment by chrisbra** [comment]
I guess I need to remove old draft release every now and then?

**Comment by k-takata** [comment]
> Or, I think we can improve the script to remove the draft release when the x86 build is failed.

Improved in #264.

**Comment by k-takata** [comment]
The x86 build is stopped at `Test_empty_command_visual_mode()` in `test_alot.vim`:

![image](https://user-images.githubusercontent.com/840186/172362499-1a6936c4-d4f0-4bda-a272-0f8b8aa35bd1.png)

**Comment by k-takata** [comment]
> > Or, I think we can improve the script to remove the draft release when the x86 build is failed.
> 
> Improved in #264.

It looks that `on_failure` is not called on a timeout.

**Comment by brammool** [comment]
> ping @brammool then

We sometimes have the problem that the test hangs because an error
dialog is displayed.  Since there is nobody to click the Ok button we
get stuck there.  Perhaps we should have a --no-gui-dialog argument to
disable this?  It would need to be checked in gui_mch_dialog().

-- 
In Africa some of the native tribes have a custom of beating the ground
with clubs and uttering spine chilling cries.  Anthropologists call
this a form of primitive self-expression.  In America we call it golf.

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by k-takata** [comment]
Now I can reproduce this in my local environment.
When I compiled with `VIMDLL=yes`, this didn't happen. But, after I changed `VIMDLL` to no, it happens frequently.

I found that mch_errmsg() is called with the following sequence, and the dialog box is shown because of this:
... -> do_one_cmd() -> ex_range_without_command() -> ex_print() -> print_line() -> print_line_no_prefix() -> ... -> mch_errmsg()

I don't know why ex_print() is called, though.


> Perhaps we should have a --no-gui-dialog argument to disable this? It would need to be checked in gui_mch_dialog().

I remember this issue: https://github.com/vim/vim/pull/7970#issuecomment-800221829
I created a trial patch, but not finished yet:
https://osdn.net/users/k_takata/pf/vim-ktakata-mq/scm/blobs/tip/add-testing-option-7970.patch

**Comment by brammool** [comment]
> Now I can reproduce this in my local environment.
> When I compiled with `VIMDLL=yes`, this didn't happen. But, after I changed `VIMDLL` to no, it happens frequently.
> 
> I found that mch_errmsg() is called with the following sequence, and the dialog box is shown because of this:
> ... -> do_one_cmd() -> ex_range_without_command() -> ex_print() -> print_line() -> print_line_no_prefix() -> ... -> mch_errmsg()
> 
> I don't know why ex_print() is called, though.

An empty line or just ":" can do this, printing the line is the default
command.  E.g. if you are in Ex mode, hitting Enter prints the current
line and moves to the next one.

Perhaps we should make a command line argument that, instead of showing
a dialog, writes the text into a file and takes the default action.
Then the test can display that text and we can figure out what is wrong.
This would be in gui_mch_dialog() so that it catches all.

-- 
MONK: ... and the Lord spake, saying, "First shalt thou take out the Holy Pin,
      then shalt thou count to three, no more, no less.  Three shalt be the
      number thou shalt count, and the number of the counting shalt be three.
      Four shalt thou not count, neither count thou two, excepting that thou
      then proceed to three.  Five is right out.  Once the number three, being
      the third number, be reached, then lobbest thou thy Holy Hand Grenade of
      Antioch towards thou foe, who being naughty in my sight, shall snuff it.
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by k-takata** [comment]
Ah, `Test_empty_command_visual_mode()` creates a file with the following content:

```
r<sfile>
0norm0V:^[
:qall!
```

and starts gvim with `-e -s -S Xexmodescript`. So, `:^[` in the second line triggers it.
But still, I don't understand why this happens on x86 frequently, but not on x84.
Vim will start in the silent mode because of the `-s` option, then no messages should be shown?

**Comment by brammool** [comment]
> Ah, `Test_empty_command_visual_mode()` creates a file with the following content:
> 
> ```
> r<sfile>
> 0norm0V:^[
> :qall!
> ```
> 
> and starts gvim with `-e -s -S Xexmodescript`. So, `:^[` in the second line triggers it.
> But still, I don't understand why this happens on x86 frequently, but not on x84.
> Vim will start in the silent mode because of the `-s` option, then no messages should be shown?

I thought so.  Perhaps on MS-Windows the silent mode is ignored somehow?

-- 
LAUNCELOT: Isn't there a St. Aaaaarrrrrrggghhh's in Cornwall?
ARTHUR:    No, that's Saint Ives.
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by chrisbra** [comment]
FWIW: I tried reproducing using MSYS build but couldn't (independently of VIMDLL). So don't know why it affects MVC (x86) builds that much

**Comment by k-takata** [comment]
Inside `print_line()`, `silent_mode` is set to FALSE and then `print_line_no_prefix()` is called.

**Comment by brammool** [comment]
> Inside `print_line()`, `silent_mode` is set to FALSE and then
> `print_line_no_prefix()` is called.

I think that is correct, in silent mode the :print command still outputs
text.

This still hints at adding a "don't show a dialog" flag to be used in
tests.

-- 
BEDEVERE:  Oooooh!
LAUNCELOT: No "Aaaaarrrrrrggghhh ... " at the back of the throat.
BEDEVERE:  No!  "Oooooh!" in surprise and alarm!
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by k-takata** [comment]
Fixed in [8.2.5084](https://github.com/vim/vim/commit/2d12c25a1b73fb6991006fd970b3132ab8ee8b62).
Thank you @brammool.

**Comment by brammool** [comment]
Ken Takata wrote:

> @brammool 
> 
> I found a suspicious behavior. Not sure whether this is the cause of the x86 issue, though.
> 
> When running the `Test_empty_command_visual_mode()` test, `parse_command_modifiers()` in ex_docmd.c is called with `eap->cmd = "'<,'>"`.
> https://github.com/vim/vim/blob/831d6d4c02ca629e7e7a28537fd9048351e5db5c/src/ex_docmd.c#L2781
> 
> So, line 2798 becomes true:
> https://github.com/vim/vim/blob/831d6d4c02ca629e7e7a28537fd9048351e5db5c/src/ex_docmd.c#L2798
> `cmd_start` points `eap->cmd + 5`.
> 
> Then `eap->cmd` is set to point `"+"`:
> https://github.com/vim/vim/blob/831d6d4c02ca629e7e7a28537fd9048351e5db5c/src/ex_docmd.c#L2824
> 
> In line 3105, `eap->cmd` and `cmd_start` are compared:
> https://github.com/vim/vim/blob/831d6d4c02ca629e7e7a28537fd9048351e5db5c/src/ex_docmd.c#L3105
> These two pointers point different strings, so this comparison is invalid.
> 
> I don't know what is expected here...

Right, this was partly fixed, but there is still a code path, in Ex
mode, where eap->cmd is used incorrectly.

I think the best is to change eap->cmd to "+" at the very end.
I'll make a patch for that, please check.

-- 
Zen Microsystems: we're the om in .commmmmmmmm

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by k-takata** [comment]
I checked [v8.2.5092](https://github.com/vim/vim/commit/48ce135e6d45e6c10ed0c0fc4cb8433bf647672a).
Now the message is shown on both x86 and x64, and even on the console version. So, the x64 behavior was wrong.

**Comment by brammool** [comment]
Ken Takata wrote:

> I checked [v8.2.5092](https://github.com/vim/vim/commit/48ce135e6d45e6c10ed0c0fc4cb8433bf647672a).
> Now the message is shown on both x86 and x64, and even on the console
> version. So, the x64 behavior was wrong.

Does this mean the problem is fixed, or that it now fails on more
platforms?

-- 
ARTHUR: If you do not open these doors, we will take this castle by force ...
   [A bucket of slops land on ARTHUR.  He tries to retain his dignity.]
                 "Monty Python and the Holy Grail" PYTHON (MONTY) PICTURES LTD

 /// Bram Moolenaar -- ***@***.*** -- http://www.Moolenaar.net   \\\
///                                                                      \\\
\\\        sponsor Vim, vote for features -- http://www.Vim.org/sponsor/ ///
 \\\            help me help AIDS victims -- http://ICCF-Holland.org    ///

**Comment by k-takata** [comment]
I actually still don't understand whether the following message should be shown or not:
```
 r<sfile>
 0norm0V:^[
```
However, the message is now shown consistently,  and the `--gui-dialog-file` option avoids that the test being stopped by the dialog box.
So, I think it is okay (for now).
